### ISSUE TITLE
Add more info to dashboard

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/escrow-dashboard#70]
Some issue cannot be gotten from the graph https://github.com/humanprotocol/escrow-dashboard/issues/62 and https://github.com/humanprotocol/escrow-dashboard/issues/61. Please ticket them both up, remembering to add tests.

**Comment by Charlie85270** [comment]
Hey @posix4e , I'll work on this one !

**Comment by posix4e** [comment]
How's this going?

**Comment by Charlie85270** [comment]
@posix4e 
I implemented the recuperation of the price.  For the holders, not all scan API return the holders informations and some are not free (MATIC). So I'm implementing the holders indexation on the graph side, this will allow us to have the list of all holders in real time and their total number for each network. My graph is currently syncing, I'll keep you update when it's over.

**Comment by foufrix** [comment]
You can test the indexation here : https://thegraph.com/hosted-service/subgraph/charlie85270/human-polygon?version=pending 
With the query :
{
  hmtokenStatistics(id:"hmt-statistics-id"){
    holders
  }
}
And here the links for the PR
- Dashboard : https://github.com/humanprotocol/escrow-dashboard/actions/runs/3176216816/jobs/5175252516
- Graph : https://github.com/humanprotocol/hmt-escrow/pull/372/files
